/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgetapp2;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author TamTam
 */
public class AddIncomeExpenses extends javax.swing.JFrame {

    /**
     * Creates new form AddIncomeExpenses
     */
    public AddIncomeExpenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incomeJPanel = new javax.swing.JPanel();
        intCategory = new javax.swing.JLabel();
        intAmount = new javax.swing.JLabel();
        intDate = new javax.swing.JLabel();
        addIncBtn = new javax.swing.JButton();
        intCatTxtBox = new javax.swing.JTextField();
        intAmountTxtBox = new javax.swing.JTextField();
        incDatePicker = new org.jdesktop.swingx.JXDatePicker();
        expensesJPanel = new javax.swing.JPanel();
        expCategory = new javax.swing.JLabel();
        expAmount = new javax.swing.JLabel();
        expDate = new javax.swing.JLabel();
        addExpBtn = new javax.swing.JButton();
        expCatTxtBox = new javax.swing.JTextField();
        expAmountTxtBox = new javax.swing.JTextField();
        expDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        incomeJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Income"));

        intCategory.setText("Category");

        intAmount.setText("Amount");

        intDate.setText("Date");

        addIncBtn.setText("Add Income");
        addIncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIncBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incomeJPanelLayout = new javax.swing.GroupLayout(incomeJPanel);
        incomeJPanel.setLayout(incomeJPanelLayout);
        incomeJPanelLayout.setHorizontalGroup(
            incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addIncBtn)
                    .addGroup(incomeJPanelLayout.createSequentialGroup()
                        .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intCategory)
                            .addComponent(intAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intCatTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        incomeJPanelLayout.setVerticalGroup(
            incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intCatTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addIncBtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        expensesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Expenses"));

        expCategory.setText("Category");

        expAmount.setText("Amount");

        expDate.setText("Date");

        addExpBtn.setText("Add Expenses");
        addExpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expensesJPanelLayout = new javax.swing.GroupLayout(expensesJPanel);
        expensesJPanel.setLayout(expensesJPanelLayout);
        expensesJPanelLayout.setHorizontalGroup(
            expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addExpBtn)
                    .addGroup(expensesJPanelLayout.createSequentialGroup()
                        .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expCategory)
                            .addComponent(expAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expCatTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        expensesJPanelLayout.setVerticalGroup(
            expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expCatTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(expensesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addExpBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(incomeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expensesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incomeJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expensesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addIncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIncBtnActionPerformed
        Income inc = new Income();
        inc.setIncCategory(intCatTxtBox.getText());
        inc.setIncAmount(Integer.parseInt(intAmountTxtBox.getText()));
        inc.setIncDate(incDatePicker.getDate());

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BudgetApp2PU");
        IncomeJpaController ijc = new IncomeJpaController(emf);
        ijc.create(inc);

        ViewIncomeExpenses si = new ViewIncomeExpenses();
        si.setVisible(true);
    }//GEN-LAST:event_addIncBtnActionPerformed

    private void addExpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpBtnActionPerformed
        Expenditure exp = new Expenditure();
        exp.setExpCategory(expCatTxtBox.getText());
        exp.setExpAmount(Integer.parseInt(expAmountTxtBox.getText()));
        exp.setExpDate(expDatePicker.getDate());

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BudgetApp2PU");
        ExpenditureJpaController ijc = new ExpenditureJpaController(emf);
        ijc.create(exp);

        ViewIncomeExpenses si = new ViewIncomeExpenses();
        si.setVisible(true);
    }//GEN-LAST:event_addExpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddIncomeExpenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpBtn;
    private javax.swing.JButton addIncBtn;
    private javax.swing.JLabel expAmount;
    private javax.swing.JTextField expAmountTxtBox;
    private javax.swing.JTextField expCatTxtBox;
    private javax.swing.JLabel expCategory;
    private javax.swing.JLabel expDate;
    private org.jdesktop.swingx.JXDatePicker expDatePicker;
    private javax.swing.JPanel expensesJPanel;
    private org.jdesktop.swingx.JXDatePicker incDatePicker;
    private javax.swing.JPanel incomeJPanel;
    private javax.swing.JLabel intAmount;
    private javax.swing.JTextField intAmountTxtBox;
    private javax.swing.JTextField intCatTxtBox;
    private javax.swing.JLabel intCategory;
    private javax.swing.JLabel intDate;
    // End of variables declaration//GEN-END:variables
}
